INSERT INTO jobs VALUES (1,'Manage the front desk , keep track of signed in guest and print entry badges.','Front Desk');
INSERT INTO jobs VALUES (2,'Organize and arrange the props on the perofrmance stage during the event.','Stage Organizer');
INSERT INTO jobs VALUES (3,'Guest Coordinator','Provide information to the guests about events, locations & details');
INSERT INTO jobs VALUES (4,'Handle food logistics, preperation & serving','Food Services');
INSERT INTO jobs VALUES (5,'Manage stationary supplies.','Stationary Services');
INSERT INTO jobs VALUES (6,'Manage security outside of each event space by controlling entry exits.','Security Personnel');
INSERT INTO jobs VALUES (7,'Act as a supervisor to the team of volunteers like. We prefer to have past history working for us in order toqualify as a supervisor.','General Supervisor');

INSERT INTO volunteers values (1,'Barry','Towne');			
INSERT INTO volunteers values (2,'Ethyl','Donnelly');			
INSERT INTO volunteers values (3,'Felipe','Breitenberg');			
INSERT INTO volunteers values (4,'Fred','Hettinger');			
INSERT INTO volunteers values (5,'Freeda','Koelpin');			
INSERT INTO volunteers values (6,'Guy','Considine');			
INSERT INTO volunteers values (7,'Gillian','Gerhold');			
INSERT INTO volunteers values (8,'Gloria','Williamson');			
INSERT INTO volunteers values (9,'Gordon','Kirlin');			
INSERT INTO volunteers values (10,'Isabell','Prosacco');			
INSERT INTO volunteers values (11,'Jacky','Renner');			
INSERT INTO volunteers values (12,'Kaitlyn','Tillman');			
INSERT INTO volunteers values (13,'Laverna','D Amore');			
INSERT INTO volunteers values (14,'Lonnie','Kreiger');			
INSERT INTO volunteers values (15,'Maeve','Hahn');			
INSERT INTO volunteers values (16,'Marcia','Corkery');			
INSERT INTO volunteers values (17,'Melyssa','Boehm');			
INSERT INTO volunteers values (18,'Muriel','Metz');			
INSERT INTO volunteers values (19,'Nat','Conn');			
INSERT INTO volunteers values (20,'Orin','Bahringer');			
INSERT INTO volunteers values (21,'Pascale','Hayes');			
INSERT INTO volunteers values (22,'Phoebe','Collier');			
INSERT INTO volunteers values (23,'Rowena','Walsh');			
INSERT INTO volunteers values (24,'Sabryna','Schowalter');			
INSERT INTO volunteers values (25,'Sahil','Pacocha');			
INSERT INTO volunteers values (26,'Sanford','Toy');			
INSERT INTO volunteers values (27,'Viola','Wisozk');			



INSERT INTO jobs_volunteers VALUES(1,6);		
INSERT INTO jobs_volunteers VALUES(1,10);		
INSERT INTO jobs_volunteers VALUES(1,12);		
INSERT INTO jobs_volunteers VALUES(1,13);		
INSERT INTO jobs_volunteers VALUES(1,16);		
INSERT INTO jobs_volunteers VALUES(1,19);		
INSERT INTO jobs_volunteers VALUES(1,20);		
INSERT INTO jobs_volunteers VALUES(1,23);		
INSERT INTO jobs_volunteers VALUES(1,24);		
INSERT INTO jobs_volunteers VALUES(2,1);		
INSERT INTO jobs_volunteers VALUES(2,7);		
INSERT INTO jobs_volunteers VALUES(2,15);		
INSERT INTO jobs_volunteers VALUES(2,17);		
INSERT INTO jobs_volunteers VALUES(2,18);		
INSERT INTO jobs_volunteers VALUES(2,22);		
INSERT INTO jobs_volunteers VALUES(2,25);		
INSERT INTO jobs_volunteers VALUES(3,2);		
INSERT INTO jobs_volunteers VALUES(3,5);		
INSERT INTO jobs_volunteers VALUES(3,8);		
INSERT INTO jobs_volunteers VALUES(3,9);		
INSERT INTO jobs_volunteers VALUES(3,10);		
INSERT INTO jobs_volunteers VALUES(3,11);		
INSERT INTO jobs_volunteers VALUES(3,13);		
INSERT INTO jobs_volunteers VALUES(3,14);		
INSERT INTO jobs_volunteers VALUES(3,18);		
INSERT INTO jobs_volunteers VALUES(3,19);		
INSERT INTO jobs_volunteers VALUES(3,20);		
INSERT INTO jobs_volunteers VALUES(3,21);		
INSERT INTO jobs_volunteers VALUES(3,22);		
INSERT INTO jobs_volunteers VALUES(3,24);		
INSERT INTO jobs_volunteers VALUES(3,27);		
INSERT INTO jobs_volunteers VALUES(4,2);		
INSERT INTO jobs_volunteers VALUES(4,3);		
INSERT INTO jobs_volunteers VALUES(4,4);		
INSERT INTO jobs_volunteers VALUES(4,6);		
INSERT INTO jobs_volunteers VALUES(4,11);		
INSERT INTO jobs_volunteers VALUES(4,16);		
INSERT INTO jobs_volunteers VALUES(4,20);		
INSERT INTO jobs_volunteers VALUES(4,21);		
INSERT INTO jobs_volunteers VALUES(4,26);		
INSERT INTO jobs_volunteers VALUES(5,3);		
INSERT INTO jobs_volunteers VALUES(5,5);		
INSERT INTO jobs_volunteers VALUES(5,14);		
INSERT INTO jobs_volunteers VALUES(5,24);		
INSERT INTO jobs_volunteers VALUES(6,5);		
INSERT INTO jobs_volunteers VALUES(6,9);		
INSERT INTO jobs_volunteers VALUES(6,11);		
INSERT INTO jobs_volunteers VALUES(6,17);		
INSERT INTO jobs_volunteers VALUES(6,21);		
INSERT INTO jobs_volunteers VALUES(6,22);		
INSERT INTO jobs_volunteers VALUES(6,25);		
INSERT INTO jobs_volunteers VALUES(7,1);		
INSERT INTO jobs_volunteers VALUES(7,3);		
INSERT INTO jobs_volunteers VALUES(7,4);		
INSERT INTO jobs_volunteers VALUES(7,7);		
INSERT INTO jobs_volunteers VALUES(7,9);		
INSERT INTO jobs_volunteers VALUES(7,10);		
INSERT INTO jobs_volunteers VALUES(7,12);		
INSERT INTO jobs_volunteers VALUES(7,16);		
INSERT INTO jobs_volunteers VALUES(7,17);		
INSERT INTO jobs_volunteers VALUES(7,23);		
INSERT INTO jobs_volunteers VALUES(7,25);		
INSERT INTO jobs_volunteers VALUES(7,26);		
INSERT INTO jobs_volunteers VALUES(7,27);		